### ISSUE TITLE
a error in the line 150 of surface.py

### ISSUE THREAD

**Issue by skyboy23** [cmi-dair/algonauts23#1]
I'm very interested in your work, and while reproducing your code I found a problem on line 150 of surface.py. 
In cortex.db.get_surf("fsaverage", "flat", hemisphere=hemisphere), you set the first parameter to "fsaverage", but the get_surf function requires that the parameter at this position is subject. Can you help me with this issue?

**Comment by clane9** [comment]
Hi, thanks for your interest! You are right that the first argument is `subject`. We are using the group average "fsaverage" subject which can be found [here](https://figshare.com/articles/dataset/fsaverage_subject_for_pycortex/9916166). You should also be able to automatically download the subject with

```python
cortex.download_subject(subject_id="fsaverage")
```

**Comment by skyboy23** [comment]
thank you so much, I have solved this problem.
